language: generic
sudo: required
branches:
  except:
    - /^v[0-9]*/
before_script:
- sudo add-apt-repository ppa:koffeinflummi/armake -y
- sudo apt-get update -y
- sudo apt-get install armake -y
script:
- export VERSION=`cat description.ext  | grep -o 'onLoadName = ".*"' | grep -o 'v[0-9.][0-9.]*'`
- armake build -w unquoted-string -w redefinition-wo-undef -w excessive-concatenation -x ".*" -x "*.pbo" -x "*.md" . 7Cav_FullSpectrum_$VERSION.Altis.pbo
- git tag $VERSION
deploy:
  if:
    branch: master
  provider: releases
  skip_cleanup: true
  file: '7Cav_FullSpectrum_$VERSION.Altis.pbo'
  on:
    branch: master
    repo: 7Cav/7Cav_FullSpectrum_V4.Altis
  name: '7th Cavalry Full Spectrum $VERSION - Altis'
  api_key:
    secure: DsShAjHwKCRwZCYs1xU3SBksANT5R16wV/IWKIl8nFlClaKtyCa89nbmQWRyv8oHhovQI75LP17+JqqZvXcAAbXdiOhrwHQm/Ewe3DUjZucxPVuhOYO2fuU1dj9Umhr/Y5fI0NUAYEx1eZm/FMUyDQ6o2ncrGn0/5IsDU9JiCVLNeL1nlKM9MtT3wtHC3vEbzI1XZnAhOGgMTxy/yJPtCtB8WNFmxiYlpvOV3yWiPykOgGmn2zxV+5S+nYKy3UTbB5xc6h6Ihr9TGXz7DnEwkVsn5YnRUhFHJmyHrqJiWzrVhxUrqOamPsyjlwH/J1FyQXqSh2GShutRlDrVqCConrkQEi/sMPHMQ4gLXqvp9YPK17wI5VxXNToO+02sFL2PO5XPLBjYMJmIA/pKiOM/DEF2ZU8k/ZHzXeRKR1dcsszNG+aNTsqck+CHZEaVqAcoGwEoSXZAhcWfTkD7SqaFxmX+KJcWR8eIdZe5AaVluuQmnZkdhHTLzmS5BC6F/yOLKVIfeQT6YTgHNgeDfGJ0fGOmOir/5WSETc5jwziTbUaoG3nhOTaOeqpYgpFfPPqlnN8M5KR56xssErzw6EkicWdpVjwpDjXIGmJZqcDtbOmv/NSJrYalh5nbZ0hOdi+G8XCcPx5qlQ6zf9dRpMVHBXTlCpilQj+Yrh+siHWTMn8=
